group 'dev.netdur.llama_cpp_dart'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'dev.netdur.llama_cpp_dart'
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 26
    }
}
