import 'prompt_format.dart';

/// Implementation of the ChatML prompt format with a "Thinking" trigger.
/// Structure:
/// <|im_start|>system
/// {content}<|im_end|>
/// <|im_start|>user
/// {content}<|im_end|>
/// <|im_start|>assistant
/// <|thought|>
class ChatMLThinkingFormat extends PromptFormat {
  ChatMLThinkingFormat()
      : super(PromptFormatType.chatmlThinking,
            inputSequence: '<|im_start|>user\n',
            outputSequence: '<|im_start|>assistant\n<|thought|>',
            systemSequence: '<|im_start|>system\n',
            stopSequence: '<|im_end|>\n');

  @override
  String formatPrompt(String prompt) {
    return '$inputSequence$prompt$stopSequence$outputSequence';
  }

  @override
  String formatMessages(List<Map<String, dynamic>> messages) {
    final buffer = StringBuffer();

    for (var message in messages) {
      final role = message['role'];
      final content = message['content'];

      if (role == 'system') {
        buffer.write('$systemSequence$content$stopSequence');
      } else if (role == 'user') {
        buffer.write('$inputSequence$content$stopSequence');
      } else if (role == 'assistant') {
        if (content != null && content.toString().isNotEmpty) {
          // For history, we use the standard assistant header,
          // assuming the content might or might not already contain <|thought|>
          // if it was generated by this format previously.
          // We avoid injecting it redundantly in history.
          buffer.write('<|im_start|>assistant\n$content$stopSequence');
        }
      }
    }

    if (messages.isNotEmpty && messages.last['role'] != 'assistant') {
      buffer.write(outputSequence);
    } else if (messages.isNotEmpty && messages.last['role'] == 'assistant') {
      final lastContent = messages.last['content'];
      if (lastContent == null || lastContent.toString().isEmpty) {
        buffer.write(outputSequence);
      }
    }

    return buffer.toString();
  }
}
