// GENERATED by tool/generate_version.sh — do not edit by hand.
// Regenerate before tagging a release.

import 'dart:ffi';

import 'ffi/library_loader.dart';

/// Build-time pin info for this binding.
final class LlamaVersion {
  LlamaVersion._();

  /// Version of the `llama_cpp_dart` package itself, mirroring
  /// `pubspec.yaml`.
  static const String package = '0.9.0-dev.2';

  /// Full SHA of the `src/llama.cpp` submodule the native artifacts
  /// in this release were built against.
  static const String llamaCppCommit =
      '5d56effdeea49413da226d4815db58f515832ead';

  /// `git describe --tags --always` output for the llama.cpp pin.
  /// Useful for "are we ahead of upstream tag bNNNN" checks.
  static const String llamaCppDescribe = 'b8963-2-g5d56effde';

  /// UTC timestamp of when this file was generated.
  static const String generatedAt = '2026-04-29T15:13:12Z';

  /// Runtime call to `llama_print_system_info()`. Returns a string with
  /// llama.cpp build date, compiler flags, and enabled backends — useful
  /// for debugging which backends actually compiled in. Requires that
  /// `LlamaLibrary.load` (or `loadFromProcess`) succeeded first.
  static String systemInfo() {
    final ptr = LlamaLibrary.bindings.llama_print_system_info();
    if (ptr == nullptr) return '';
    final bytes = <int>[];
    var i = 0;
    while (true) {
      final c = (ptr + i).value;
      if (c == 0) break;
      bytes.add(c);
      i++;
    }
    return String.fromCharCodes(bytes);
  }
}
