// GENERATED by tool/generate_version.sh — do not edit by hand.
// Regenerate before tagging a release.

import 'dart:ffi';

import 'ffi/library_loader.dart';

/// Build-time pin info for this binding.
final class LlamaVersion {
  LlamaVersion._();

  /// Version of the `llama_cpp_dart` package itself, mirroring
  /// `pubspec.yaml`.
  static const String package = '0.9.0-dev.7';

  /// Full SHA of the `src/llama.cpp` submodule the native artifacts
  /// in this release were built against.
  static const String llamaCppCommit =
      '6b4e4bd582e457a47ee7cd498058495f47fee228';

  /// Author/committer date of [llamaCppCommit] in ISO-8601 form.
  /// Reproducible across machines (does not depend on local clock).
  static const String llamaCppCommitDate = '2026-05-27T14:52:47+03:00';

  /// Runtime call to `llama_print_system_info()`. Returns a string with
  /// llama.cpp build date, compiler flags, and enabled backends — useful
  /// for debugging which backends actually compiled in. Requires that
  /// `LlamaLibrary.load` (or `loadFromProcess`) succeeded first.
  static String systemInfo() {
    final ptr = LlamaLibrary.bindings.llama_print_system_info();
    if (ptr == nullptr) return '';
    final bytes = <int>[];
    var i = 0;
    while (true) {
      final c = (ptr + i).value;
      if (c == 0) break;
      bytes.add(c);
      i++;
    }
    return String.fromCharCodes(bytes);
  }
}
