#!/usr/bin/env bash
# Generate lib/src/version.dart with the package version + llama.cpp
# submodule pin. Run before tagging a release so users can introspect
# the binding's llama.cpp pin at runtime.
#
# Output is deterministic: same pubspec.yaml + same submodule commit ⇒
# byte-identical version.dart. CI relies on this to catch drift.
set -euo pipefail

cd "$(dirname "$0")/.."

PKG_VERSION=$(awk '/^version:/ {print $2}' pubspec.yaml)
LCPP_COMMIT=$(git -C src/llama.cpp rev-parse HEAD)
LCPP_COMMIT_DATE=$(git -C src/llama.cpp show -s --format=%cI "$LCPP_COMMIT")

cat > lib/src/version.dart <<EOF
// GENERATED by tool/generate_version.sh — do not edit by hand.
// Regenerate before tagging a release.

import 'dart:ffi';

import 'ffi/library_loader.dart';

/// Build-time pin info for this binding.
final class LlamaVersion {
  LlamaVersion._();

  /// Version of the \`llama_cpp_dart\` package itself, mirroring
  /// \`pubspec.yaml\`.
  static const String package = '$PKG_VERSION';

  /// Full SHA of the \`src/llama.cpp\` submodule the native artifacts
  /// in this release were built against.
  static const String llamaCppCommit = '$LCPP_COMMIT';

  /// Author/committer date of [llamaCppCommit] in ISO-8601 form.
  /// Reproducible across machines (does not depend on local clock).
  static const String llamaCppCommitDate = '$LCPP_COMMIT_DATE';

  /// Runtime call to \`llama_print_system_info()\`. Returns a string with
  /// llama.cpp build date, compiler flags, and enabled backends — useful
  /// for debugging which backends actually compiled in. Requires that
  /// \`LlamaLibrary.load\` (or \`loadFromProcess\`) succeeded first.
  static String systemInfo() {
    final ptr = LlamaLibrary.bindings.llama_print_system_info();
    if (ptr == nullptr) return '';
    final bytes = <int>[];
    var i = 0;
    while (true) {
      final c = (ptr + i).value;
      if (c == 0) break;
      bytes.add(c);
      i++;
    }
    return String.fromCharCodes(bytes);
  }
}
EOF

echo "wrote lib/src/version.dart:"
echo "  package            = $PKG_VERSION"
echo "  llamaCppCommit     = $LCPP_COMMIT"
echo "  llamaCppCommitDate = $LCPP_COMMIT_DATE"
